# Generated by Django 4.2.1 on 2023-06-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('tecnica', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('imagen', models.ImageField(upload_to='productos/')),
            ],
        ),
    ]
